import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Link } from 'react-router-dom';
import { useChallengeTwoFactor } from '@/hooks/useTwoFactor';
import { useAuthStore } from '@/store/authStore';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/Card';
import { KeyRound, Smartphone } from 'lucide-react';
import { cn } from '@/lib/utils';

interface TwoFactorChallengeFormProps {
  className?: string;
}

type ChallengeMode = 'code' | 'recovery';

interface ChallengeFormValues {
  code: string;
  recovery_code: string;
}

function buildSchema(mode: ChallengeMode) {
  return z.object({
    code:
      mode === 'code'
        ? z.string().regex(/^\d{6}$/, 'Enter the 6-digit code from your authenticator app')
        : z.string().optional(),
    recovery_code:
      mode === 'recovery'
        ? z.string().min(8, 'Enter a valid recovery code')
        : z.string().optional(),
  });
}

export function TwoFactorChallengeForm({ className }: TwoFactorChallengeFormProps) {
  const [mode, setMode] = useState<ChallengeMode>('code');
  const challenge = useChallengeTwoFactor();

  const {
    register,
    handleSubmit,
    setValue,
    formState: { errors },
  } = useForm<ChallengeFormValues>({
    resolver: zodResolver(buildSchema(mode)),
    defaultValues: { code: '', recovery_code: '' },
  });

  const onSubmit = (values: ChallengeFormValues) => {
    if (mode === 'code') {
      challenge.mutate({ code: values.code });
    } else {
      challenge.mutate({ recovery_code: values.recovery_code });
    }
  };

  const handleCodeChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value.replace(/\D/g, '').slice(0, 6);
    setValue('code', value, { shouldValidate: true });
    if (value.length === 6) {
      handleSubmit(onSubmit)();
    }
  };

  return (
    <Card className={cn('w-full', className)}>
      <CardHeader className="items-center text-center">
        <div className="mb-2 flex h-14 w-14 items-center justify-center rounded-full bg-brand-100">
          {mode === 'code' ? (
            <Smartphone className="h-7 w-7 text-brand-600" />
          ) : (
            <KeyRound className="h-7 w-7 text-brand-600" />
          )}
        </div>
        <CardTitle className="text-xl">
          {mode === 'code' ? 'Two-Factor Authentication' : 'Use a recovery code'}
        </CardTitle>
        <CardDescription>
          {mode === 'code'
            ? 'Enter the 6-digit verification code generated by your authenticator app.'
            : 'Enter one of the recovery codes you saved when enabling two-factor authentication.'}
        </CardDescription>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          {mode === 'code' ? (
            <Input
              label="Verification Code"
              placeholder="000000"
              inputMode="numeric"
              autoComplete="one-time-code"
              maxLength={6}
              error={errors.code?.message}
              {...register('code')}
              onChange={handleCodeChange}
            />
          ) : (
            <Input
              label="Recovery Code"
              placeholder="Enter your recovery code"
              autoComplete="off"
              error={errors.recovery_code?.message}
              {...register('recovery_code')}
            />
          )}

          <Button type="submit" className="w-full" loading={challenge.isPending}>
            Verify
          </Button>

          <button
            type="button"
            onClick={() => {
              setMode((prev) => (prev === 'code' ? 'recovery' : 'code'));
            }}
            className="w-full text-center text-sm font-medium text-brand-600 hover:text-brand-700"
          >
            {mode === 'code'
              ? 'Use a recovery code instead'
              : 'Back to authenticator app code'}
          </button>
        </form>
      </CardContent>
    </Card>
  );
}

export function TwoFactorChallengeBackLink() {
  const clearRequiresTwoFactor = useAuthStore((state) => state.clearRequiresTwoFactor);
  return (
    <p className="mt-6 text-center text-sm text-slate-500">
      <Link
        to="/login"
        onClick={clearRequiresTwoFactor}
        className="font-medium text-brand-600 hover:text-brand-700"
      >
        Back to login
      </Link>
    </p>
  );
}
